(async()=>{
  const cfg=window.CHRIST_CONNECT_CONFIG;
  const {client,session}=await window.CC_AUTH_READY;
  if(!session){location.href='portal.html';return;}
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const shopStrip=document.querySelector('#shopStrip'),menuGrid=document.querySelector('#menuGrid'),cartItems=document.querySelector('#cartItems'),cartTotal=document.querySelector('#cartTotal'),shopTitle=document.querySelector('#shopTitle'),history=document.querySelector('#orderHistory'),message=document.querySelector('#orderMessage'),placeBtn=document.querySelector('#placeOrder');
  const pickupDate=document.querySelector('#pickupDate'); pickupDate.value=new Date().toISOString().slice(0,10); pickupDate.min=pickupDate.value;
  let shops=[],items=[],selectedShop=null,cart=new Map();
  async function rest(path,opts={}){const {data:{session:s}}=await client.auth.getSession();if(!s)throw new Error('Session expired');const r=await fetch(`${cfg.SUPABASE_URL}/rest/v1/${path}`,{...opts,headers:{apikey:cfg.SUPABASE_ANON_KEY,Authorization:`Bearer ${s.access_token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json();}
  function renderShops(){shopStrip.innerHTML=shops.map(s=>`<button class="shop-btn ${selectedShop?.id===s.id?'active':''}" data-shop="${s.id}"><span>${esc(s.location||'CAMPUS DINING')}</span><b>${esc(s.name)}</b></button>`).join('');shopStrip.querySelectorAll('[data-shop]').forEach(b=>b.onclick=()=>{selectedShop=shops.find(s=>s.id===b.dataset.shop);cart=new Map();renderShops();renderMenu();renderCart();});}
  function renderMenu(){if(!selectedShop){shopTitle.textContent='Select an outlet.';menuGrid.innerHTML='';return;}shopTitle.textContent=selectedShop.name;const rows=items.filter(x=>x.shop_id===selectedShop.id);menuGrid.innerHTML=rows.length?rows.map(x=>{const q=cart.get(x.id)||0;return `<article class="menu-card"><span class="pill">${esc(x.category||'CAMPUS FOOD')}</span><h3>${esc(x.name)}</h3><p>${esc(x.description||'Demo menu item')} · approx. ${x.prep_minutes} min</p><div class="menu-bottom"><strong>₹${Number(x.price).toFixed(0)}</strong><div class="qty"><button data-dec="${x.id}" aria-label="Decrease">−</button><b>${q}</b><button data-inc="${x.id}" aria-label="Increase">+</button></div></div></article>`}).join(''):'<div class="empty-cart">No menu items loaded for this outlet.</div>';menuGrid.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));menuGrid.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));}
  function changeQty(id,d){const n=Math.max(0,(cart.get(id)||0)+d);if(n===0)cart.delete(id);else cart.set(id,n);renderMenu();renderCart();}
  function renderCart(){const rows=[...cart.entries()].map(([id,q])=>({item:items.find(x=>x.id===id),q})).filter(x=>x.item);if(!rows.length){cartItems.innerHTML='<div class="empty-cart">Nothing here yet.</div>';cartTotal.textContent='₹0';return;}let total=0;cartItems.innerHTML=rows.map(({item,q})=>{total+=Number(item.price)*q;return `<div class="cart-row"><div><b>${esc(item.name)}</b><span>${q} × ₹${Number(item.price).toFixed(0)}</span></div><div class="mini-qty"><button data-dec="${item.id}">−</button><b>${q}</b><button data-inc="${item.id}">+</button></div><strong>₹${(Number(item.price)*q).toFixed(0)}</strong></div>`}).join('');cartTotal.textContent=`₹${total.toFixed(0)}`;cartItems.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));cartItems.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));}
  async function loadWallet(){try{const w=await rest('student_wallets?select=balance');const b=Number(w?.[0]?.balance||0);let el=document.querySelector('#walletChip');if(!el){el=document.createElement('div');el.id='walletChip';el.className='tiny-note';el.style.cssText='font-weight:800;margin:6px 0';document.querySelector('.order-total')?.before(el);}el.textContent='Wallet balance: ₹'+b.toFixed(0)+' · prepaid only';}catch(e){console.error(e)}}
  const fmt=d=>new Date(d).toLocaleString('en-IN',{dateStyle:'medium',timeStyle:'short'});
  async function loadHistory(){const rows=await rest('canteen_orders?select=id,order_code,status,total,pickup_date,pickup_slot,created_at,cancel_until,canteen_shops(name)&order=created_at.desc&limit=6');history.innerHTML=rows.length?rows.map(x=>{const open=x.status==='placed'&&new Date(x.cancel_until)>new Date();return `<article class="history-card"><span>${fmt(x.created_at)}</span><b>${esc(x.canteen_shops?.name||'Campus dining')}</b><span>${esc(x.pickup_date)} · ${esc(x.pickup_slot)}</span><strong>₹${Number(x.total).toFixed(0)}</strong><div class="status ${x.status==='cancelled'?'cancelled':''}">${esc(x.status)} · ${esc(x.order_code||'')}</div><div style="display:flex;gap:8px;margin-top:8px"><button class="pill" data-receipt="${x.id}">E-receipt</button>${open?`<button class="pill" data-cancel="${x.id}" data-until="${x.cancel_until}">Cancel · <span>2:00</span></button>`:''}</div></article>`}).join(''):'<div class="empty-cart">No pre-orders yet.</div>';
    history.querySelectorAll('[data-receipt]').forEach(b=>b.onclick=()=>showReceipt(b.dataset.receipt));
    history.querySelectorAll('[data-cancel]').forEach(b=>{b.onclick=async()=>{try{const {error}=await client.rpc('cancel_canteen_order',{p_order_id:b.dataset.cancel});if(error)throw error;message.textContent='Order cancelled and refunded to your wallet.';}catch(e){message.textContent=e.message}await loadHistory();loadWallet();};
      const tick=()=>{const left=Math.floor((new Date(b.dataset.until)-Date.now())/1000);if(left<=0){b.remove();return}b.querySelector('span').textContent=Math.floor(left/60)+':'+String(left%60).padStart(2,'0');setTimeout(tick,1000)};tick();});}
  async function showReceipt(id){const {data:r,error}=await client.rpc('get_order_receipt',{p_order_id:id});if(error||!r){message.textContent='Could not load receipt.';return}
    let m=document.querySelector('#receiptModal');if(!m){m=document.createElement('div');m.id='receiptModal';m.style.cssText='position:fixed;inset:0;background:#182b3899;display:grid;place-items:center;z-index:99;padding:16px';document.body.appendChild(m);m.onclick=e=>{if(e.target===m)m.remove()}}
    m.innerHTML=`<div style="background:#fffdf7;border-radius:22px;padding:28px;max-width:400px;width:100%;font-size:13px;box-shadow:0 28px 80px #0005"><p class="eyebrow">E-RECEIPT · ${esc(r.payment_status.toUpperCase())}</p><h2 style="font:600 28px 'Playfair Display',serif;margin:4px 0">${esc(r.order_code)}</h2><p><b>${esc(r.student_name)}</b><br>Reg. no. ${esc(r.registration_number)}</p><p>${esc(r.outlet)} · ${esc(r.location||'')}<br>Placed ${fmt(r.placed_at)}<br>Pickup ${esc(r.pickup_date)} · ${esc(r.pickup_slot)}</p><hr>${r.items.map(i=>`<div style="display:flex;justify-content:space-between"><span>${i.qty} × ${esc(i.name)}</span><b>₹${Number(i.line_total).toFixed(0)}</b></div>`).join('')}<hr><div style="display:flex;justify-content:space-between;font-size:16px"><span>Total paid</span><b>₹${Number(r.total).toFixed(0)}</b></div><p style="color:#718087;font-size:11px">Status: ${esc(r.status)}. Orders can be cancelled only within 2 minutes of placing.</p><button class="pill" onclick="this.closest('#receiptModal').remove()">Close</button></div>`;}
  placeBtn.onclick=async()=>{if(!selectedShop){message.textContent='Choose an outlet first.';return;}if(!cart.size){message.textContent='Add at least one item.';return;}placeBtn.disabled=true;message.textContent='Placing your pre-order…';try{const payload=[...cart.entries()].map(([item_id,quantity])=>({item_id,quantity}));const slot=document.querySelector('#pickupSlot').value;const notes=document.querySelector('#orderNotes').value.trim();const {data:result,error}=await client.rpc('place_canteen_preorder',{p_shop_id:selectedShop.id,p_pickup_date:pickupDate.value,p_pickup_slot:slot,p_notes:notes||null,p_items:payload});if(error)throw error;const order=result?.[0]||result;message.textContent=`Order ${order.order_code||''} paid · ₹${Number(order.total||0).toFixed(0)}. You can cancel for 2 minutes.`;cart=new Map();renderCart();renderMenu();await loadHistory();loadWallet();showReceipt(order.order_id);}catch(e){console.error(e);message.textContent=e.message||'Could not place the pre-order.';}finally{placeBtn.disabled=false;}};
  try{shops=await rest('canteen_shops?select=id,name,location,description&order=location,name');items=await rest('canteen_items?select=id,shop_id,name,category,price,description,prep_minutes&order=category,name');selectedShop=shops[0]||null;renderShops();renderMenu();renderCart();await loadHistory();await loadWallet();document.querySelectorAll('.reveal').forEach(el=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.08});io.observe(el);});}catch(e){console.error(e);message.textContent='Canteen data could not load. Run supabase/upgrade_v3.sql first.';}
})();
