(async()=>{
  const cfg=window.CHRIST_CONNECT_CONFIG;
  const {client,session}=await window.CC_AUTH_READY;
  if(!session){location.href='portal.html';return;}
  const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const shopStrip=document.querySelector('#shopStrip'),menuGrid=document.querySelector('#menuGrid'),cartItems=document.querySelector('#cartItems'),cartTotal=document.querySelector('#cartTotal'),shopTitle=document.querySelector('#shopTitle'),history=document.querySelector('#orderHistory'),message=document.querySelector('#orderMessage'),placeBtn=document.querySelector('#placeOrder');
  const pickupDate=document.querySelector('#pickupDate'); pickupDate.value=new Date().toISOString().slice(0,10); pickupDate.min=pickupDate.value;
  let shops=[],items=[],selectedShop=null,cart=new Map();
  async function rest(path,opts={}){const {data:{session:s}}=await client.auth.getSession();if(!s)throw new Error('Session expired');const r=await fetch(`${cfg.SUPABASE_URL}/rest/v1/${path}`,{...opts,headers:{apikey:cfg.SUPABASE_ANON_KEY,Authorization:`Bearer ${s.access_token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json();}
  function renderShops(){shopStrip.innerHTML=shops.map(s=>`<button class="shop-btn ${selectedShop?.id===s.id?'active':''}" data-shop="${s.id}"><span>${esc(s.location||'CAMPUS DINING')}</span><b>${esc(s.name)}</b></button>`).join('');shopStrip.querySelectorAll('[data-shop]').forEach(b=>b.onclick=()=>{selectedShop=shops.find(s=>s.id===b.dataset.shop);cart=new Map();renderShops();renderMenu();renderCart();});}
  function renderMenu(){if(!selectedShop){shopTitle.textContent='Select an outlet.';menuGrid.innerHTML='';return;}shopTitle.textContent=selectedShop.name;const rows=items.filter(x=>x.shop_id===selectedShop.id);menuGrid.innerHTML=rows.length?rows.map(x=>{const q=cart.get(x.id)||0;return `<article class="menu-card"><span class="pill">${esc(x.category||'CAMPUS FOOD')}</span><h3>${esc(x.name)}</h3><p>${esc(x.description||'Demo menu item')} · approx. ${x.prep_minutes} min</p><div class="menu-bottom"><strong>₹${Number(x.price).toFixed(0)}</strong><div class="qty"><button data-dec="${x.id}" aria-label="Decrease">−</button><b>${q}</b><button data-inc="${x.id}" aria-label="Increase">+</button></div></div></article>`}).join(''):'<div class="empty-cart">No menu items loaded for this outlet.</div>';menuGrid.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));menuGrid.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));}
  function changeQty(id,d){const n=Math.max(0,(cart.get(id)||0)+d);if(n===0)cart.delete(id);else cart.set(id,n);renderMenu();renderCart();}
  function renderCart(){const rows=[...cart.entries()].map(([id,q])=>({item:items.find(x=>x.id===id),q})).filter(x=>x.item);if(!rows.length){cartItems.innerHTML='<div class="empty-cart">Nothing here yet.</div>';cartTotal.textContent='₹0';return;}let total=0;cartItems.innerHTML=rows.map(({item,q})=>{total+=Number(item.price)*q;return `<div class="cart-row"><div><b>${esc(item.name)}</b><span>${q} × ₹${Number(item.price).toFixed(0)}</span></div><div class="mini-qty"><button data-dec="${item.id}">−</button><b>${q}</b><button data-inc="${item.id}">+</button></div><strong>₹${(Number(item.price)*q).toFixed(0)}</strong></div>`}).join('');cartTotal.textContent=`₹${total.toFixed(0)}`;cartItems.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));cartItems.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1));}
  async function loadHistory(){const rows=await rest('canteen_orders?select=id,order_code,status,total,pickup_date,pickup_slot,created_at,canteen_shops(name)&order=created_at.desc&limit=6');history.innerHTML=rows.length?rows.map(x=>`<article class="history-card"><span>${new Date(x.created_at).toLocaleString()}</span><b>${esc(x.canteen_shops?.name||'Campus dining')}</b><span>${esc(x.pickup_date)} · ${esc(x.pickup_slot)}</span><strong>₹${Number(x.total).toFixed(0)}</strong><div class="status ${x.status==='cancelled'?'cancelled':''}">${esc(x.status)} · ${esc(x.order_code||'')}</div></article>`).join(''):'<div class="empty-cart">No pre-orders yet.</div>';}
  placeBtn.onclick=async()=>{if(!selectedShop){message.textContent='Choose an outlet first.';return;}if(!cart.size){message.textContent='Add at least one item.';return;}placeBtn.disabled=true;message.textContent='Placing your pre-order…';try{const payload=[...cart.entries()].map(([item_id,quantity])=>({item_id,quantity}));const slot=document.querySelector('#pickupSlot').value;const notes=document.querySelector('#orderNotes').value.trim();const {data:result,error}=await client.rpc('place_canteen_preorder',{p_shop_id:selectedShop.id,p_pickup_date:pickupDate.value,p_pickup_slot:slot,p_notes:notes||null,p_items:payload});if(error)throw error;const order=result?.[0]||result;message.textContent=`Order ${order.order_code||''} placed · ₹${Number(order.total||0).toFixed(0)}. Show the code at pickup.`;cart=new Map();renderCart();renderMenu();await loadHistory();}catch(e){console.error(e);message.textContent=e.message||'Could not place the pre-order.';}finally{placeBtn.disabled=false;}};
  try{shops=await rest('canteen_shops?select=id,name,location,description&order=location,name');items=await rest('canteen_items?select=id,shop_id,name,category,price,description,prep_minutes&order=category,name');selectedShop=shops[0]||null;renderShops();renderMenu();renderCart();await loadHistory();document.querySelectorAll('.reveal').forEach(el=>{const io=new IntersectionObserver(es=>es.forEach(e=>e.isIntersecting&&e.target.classList.add('visible')),{threshold:.08});io.observe(el);});}catch(e){console.error(e);message.textContent='Canteen data could not load. Run supabase/upgrade_v3.sql first.';}
})();
