(async()=>{await window.CC_AUTH_READY;
const cfg=window.CHRIST_CONNECT_CONFIG;
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(path,opts={}){if(!cfg?.SUPABASE_URL)throw new Error('Supabase configuration missing');const {session}=await window.CC_AUTH_READY; if(!session) throw new Error('Session expired'); const r=await fetch(`${cfg.SUPABASE_URL}/rest/v1/${path}`,{...opts,headers:{apikey:cfg.SUPABASE_ANON_KEY,Authorization:`Bearer ${session.access_token}`,...(opts.headers||{})}});if(!r.ok)throw new Error(await r.text());return r.status===204?null:r.json()}
const pct=(a,h)=>h?Math.round((a/h)*1000)/10:null;
let attendanceRows=[];let selected=null;
function statsFor(rows){const held=rows.reduce((n,r)=>n+Number(r.sessions_held||0),0);const attended=rows.reduce((n,r)=>n+Number(r.sessions_attended||0),0);return {held,attended,pct:pct(attended,held)}}
function calc(row){const target=Number(document.querySelector('#targetPercent').value)||75;const attendN=Math.max(0,Number(document.querySelector('#futureAttend').value)||0);const missN=Math.max(0,Number(document.querySelector('#futureMiss').value)||0);const h=Number(row.sessions_held),a=Number(row.sessions_attended);const current=pct(a,h);const afterAttend=pct(a+attendN,h+attendN);const afterMiss=pct(a,h+missN);const rawCanMiss=a*100/target-h;const canMiss=Math.max(0,Math.floor(rawCanMiss+1e-9));let need=0;if(target<100 && a/h*100<target){need=Math.max(0,Math.ceil((target*h-100*a)/(100-target)-1e-9));}document.querySelector('#afterAttend').textContent=`${afterAttend.toFixed(1)}%`;document.querySelector('#afterMiss').textContent=`${afterMiss.toFixed(1)}%`;document.querySelector('#attendDelta').textContent=`${afterAttend-current>=0?'+':''}${(afterAttend-current).toFixed(1)} pts`;document.querySelector('#missDelta').textContent=`${afterMiss-current>=0?'+':''}${(afterMiss-current).toFixed(1)} pts`;document.querySelector('#canMiss').textContent=`${canMiss}`;document.querySelector('#needAttend').textContent=`${need}`;document.querySelector('#calcSummary').textContent=`${row.course_name}: ${a}/${h} classes attended.`}
function selectRow(i){selected=i;document.querySelectorAll('.attendance-card').forEach((el,idx)=>el.classList.toggle('selected',idx===i));document.querySelector('#calculator').hidden=false;calc(attendanceRows[i]);}
function renderAttendance(){const grid=document.querySelector('#attendanceGrid');if(!attendanceRows.length){grid.innerHTML='<div class="loading-card">No attendance records have been provisioned for this account yet.</div>';return}grid.innerHTML=attendanceRows.map((r,i)=>{const p=pct(r.sessions_attended,r.sessions_held)||0;const target=Number(document.querySelector('#targetPercent').value)||75;const ok=p>=target;return `<article class="attendance-card ${selected===i?'selected':''}" data-index="${i}"><span class="code">${esc(r.course_code)}</span><h3>${esc(r.course_name)}</h3><div class="percent-row"><b>${p.toFixed(1)}%</b><small>${r.sessions_attended}/${r.sessions_held} attended</small></div><div class="bar"><i style="width:${Math.min(100,p)}%"></i></div><span class="status ${ok?'good':'warn'}">${ok?'ABOVE TARGET':'BELOW TARGET'}</span></article>`}).join('');grid.querySelectorAll('[data-index]').forEach(el=>el.addEventListener('click',()=>selectRow(Number(el.dataset.index))));if(selected==null)selectRow(0);else if(attendanceRows[selected]){document.querySelector('#calculator').hidden=false;calc(attendanceRows[selected])}}
async function load(){try{
const p=(await api('student_profiles?select=*&limit=1'))[0];if(!p)throw new Error('Student profile not found');
document.querySelector('#greeting').textContent=`Welcome back, ${p.full_name.split(/\s+/)[0]}.`;
document.querySelector('#heroReg').textContent=`${p.registration_number}`;document.querySelector('#heroProgram').textContent=[p.programme,p.department].filter(Boolean).join(' · ')||'Student';
document.querySelector('#studentName').textContent=esc(p.full_name);document.querySelector('#studentCourse').textContent=[p.programme,p.department,p.school].filter(Boolean).join(' · ')||'Student';document.querySelector('#profileReg').textContent=p.registration_number||'—';document.querySelector('#profileStatus').textContent=p.status||'—';document.querySelector('#profileBatch').textContent=p.batch_year||'—';
const initials=p.full_name.split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join('').toUpperCase();document.querySelector('#headAvatar').textContent=initials||'CC';document.querySelector('.orb-inner').textContent=initials||'CC';
attendanceRows=await api('attendance_records?select=course_code,course_name,sessions_held,sessions_attended&order=course_name');const totals=statsFor(attendanceRows);document.querySelector('#attendance').textContent=totals.pct==null?'—':`${totals.pct.toFixed(1)}%`;document.querySelector('#attendanceLabel').textContent=totals.held?`${totals.attended}/${totals.held} classes attended`:'No records yet';renderAttendance();
const ev=await api('event_registrations?select=event_id');document.querySelector('#eventsCount').textContent=ev.length;const clubs=await api('club_memberships?select=club_id');document.querySelector('#clubsCount').textContent=clubs.length;const n=await api('notifications?select=id,is_read&is_read=eq.false');document.querySelector('#noticeCount').textContent=n.length;
const complete=[p.full_name,p.programme,p.department,p.batch_year,p.university_email,p.bio].filter(Boolean).length;const cp=Math.round(complete/6*100);document.querySelector('#profileMeter').style.width=`${cp}%`;document.querySelector('#profileHint').textContent=`Profile ${cp}% complete`;
const notes=await api('notifications?select=title,body,created_at&order=created_at.desc&limit=4');document.querySelector('#notifications').innerHTML=notes.length?notes.map(n=>`<div class="notice"><div><b>${esc(n.title)}</b><small>${esc(n.body||'')}</small></div></div>`).join(''):'<small>No notifications yet.</small>';
const regs=await api('event_registrations?select=event_id,registered_at,events(title,starts_at,location,description)&order=registered_at.desc&limit=6');document.querySelector('#eventsList').innerHTML=regs.length?regs.map(r=>`<div class="event"><div><b>${esc(r.events?.title||'Campus event')}</b><small>${esc(r.events?.location||'Campus')} · ${r.events?.starts_at?new Date(r.events.starts_at).toLocaleString():''}</small></div></div>`).join(''):'<small>No registered events yet.</small>';
}catch(e){console.error(e);document.querySelector('#eventsList').innerHTML='<small>Unable to load your private dashboard data. Check the Supabase session and RLS policies.</small>';document.querySelector('#attendanceGrid').innerHTML='<div class="loading-card">Your attendance could not be loaded.</div>'}}
document.querySelector('#targetPercent').addEventListener('input',renderAttendance);document.querySelector('#futureAttend').addEventListener('input',()=>selected!=null&&calc(attendanceRows[selected]));document.querySelector('#futureMiss').addEventListener('input',()=>selected!=null&&calc(attendanceRows[selected]));document.querySelector('#logout').addEventListener('click',async()=>{await (await window.CC_AUTH_READY).client.auth.signOut();location.href='portal.html'});document.querySelectorAll('.reveal').forEach(el=>new IntersectionObserver(es=>es.forEach(x=>{if(x.isIntersecting){x.target.classList.add('visible');}}),{threshold:.08}).observe(el));load();

})().catch(e=>{console.error(e);location.href='portal.html'});
