(async()=>{
  const s=await CC_AUTH.requireAuth(); if(!s)return; const c=await CC_AUTH.init();
  const {data:p,error:pe}=await c.from('student_profiles').select('*').eq('id',s.user.id).single(); if(pe){document.querySelector('#subline').textContent='We could not load your student profile yet.';return}
  const name=p.full_name||'Student'; const parts=name.trim().split(/\s+/); const initials=(parts[0]?.[0]||'S')+(parts[1]?.[0]||'');
  document.querySelector('#greeting').innerHTML=`Welcome <em>${escapeHtml(parts[0]||'back')}.</em>`;document.querySelector('#heroInitials').textContent=initials.toUpperCase();document.querySelector('#heroReg').textContent=`${p.registration_number}`;document.querySelector('#heroProgramme').textContent=`${p.programme||'Programme not set'}`;document.querySelector('#studentName').innerHTML=`${escapeHtml(name)} <em>profile.</em>`;document.querySelector('#studentEmail').textContent=p.university_email||'—';document.querySelector('#studentSchool').textContent=p.school||'—';document.querySelector('#studentDepartment').textContent=p.department||'—';document.querySelector('#studentStatus').textContent=p.status||'—';
  const {data:att=[]}=await c.from('attendance_records').select('*').eq('student_id',s.user.id).order('course_name');renderAttendance(att);
  const avg=att.length?att.reduce((a,x)=>a+(x.sessions_held?x.sessions_attended/x.sessions_held*100:0),0)/att.length:null;document.querySelector('#overall').textContent=avg==null?'—':`${avg.toFixed(1)}%`;document.querySelector('#overallMeta').textContent=avg==null?'No attendance rows yet':`${att.length} subjects loaded`;
  const {count:eventCount}=await c.from('event_registrations').select('*',{count:'exact',head:true}).eq('student_id',s.user.id);document.querySelector('#eventCount').textContent=eventCount??0;
  const {count:clubCount}=await c.from('club_memberships').select('*',{count:'exact',head:true}).eq('student_id',s.user.id);document.querySelector('#clubCount').textContent=clubCount??0;
  const {data:notices=[]}=await c.from('notifications').select('title,body,created_at,is_read').eq('student_id',s.user.id).order('created_at',{ascending:false}).limit(4);document.querySelector('#noticeCount').textContent=notices.filter(x=>!x.is_read).length;document.querySelector('#notifications').innerHTML=notices.length?notices.map(x=>`<div class="data-row"><small>${new Date(x.created_at).toLocaleString()}</small><b>${escapeHtml(x.title)}${x.is_read?'':' · NEW'}<br><span class="muted">${escapeHtml(x.body||'')}</span></b></div>`).join(''):'<p class="muted">No notifications yet.</p>';
  document.querySelector('#logout').onclick=()=>CC_AUTH.signOut();
  function renderAttendance(rows){const grid=document.querySelector('#attendanceGrid');if(!rows.length){grid.innerHTML='<div class="student-card">No attendance data has been provisioned for this account.</div>';return}grid.innerHTML=rows.map((x,i)=>{const pct=x.sessions_held?x.sessions_attended/x.sessions_held*100:0;return `<button class="attendance-live reveal" data-i="${i}"><div class="subject">${escapeHtml(x.course_name)}</div><div class="code">${escapeHtml(x.course_code)}</div><div class="pct">${pct.toFixed(1)}%</div><div class="progress"><i style="width:${Math.min(100,pct)}%"></i></div><small>${x.sessions_attended} attended / ${x.sessions_held} held</small></button>`}).join('');grid.querySelectorAll('[data-i]').forEach(b=>b.onclick=()=>select(rows[Number(b.dataset.i)]));select(rows[0])}
  function select(x){document.querySelector('#attendanceTools').hidden=false;document.querySelector('#calcTitle').textContent=x.course_name;document.querySelector('#calcSummary').textContent=`${x.sessions_attended} of ${x.sessions_held} classes attended · current ${(x.sessions_attended/x.sessions_held*100).toFixed(1)}%`;['target','futureAttend','futureMiss'].forEach(id=>document.querySelector('#'+id).oninput=()=>calc(x));calc(x)}
  function calc(x){const t=Number(document.querySelector('#target').value)/100,a=x.sessions_attended,h=x.sessions_held,fa=Number(document.querySelector('#futureAttend').value)||0,fm=Number(document.querySelector('#futureMiss').value)||0;const cur=h?a/h*100:0;const aa=(a+fa)/(h+fa)*100;const am=a/(h+fm)*100;const canMiss=t>0?Math.max(0,Math.floor(a/t-h+1e-9)):0;const need=cur>=t*100?0:Math.max(0,Math.ceil((t*h-a)/(1-t)));document.querySelector('#afterAttend').textContent=`${aa.toFixed(1)}%`;document.querySelector('#attendDelta').textContent=`${(aa-cur>=0?'+':'')+(aa-cur).toFixed(1)} pts`;document.querySelector('#afterMiss').textContent=`${am.toFixed(1)}%`;document.querySelector('#missDelta').textContent=`${(am-cur>=0?'+':'')+(am-cur).toFixed(1)} pts`;document.querySelector('#canMiss').textContent=canMiss;document.querySelector('#needAttend').textContent=need}
  function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
})();
