const key=document.body.dataset.eventPage||'events';
const items=[
 ['PLACETRIALS 2026','School of Sciences','Current Delhi NCR campus activity feed','green'],
 ['TARANG 2026','School of Sciences','Current Delhi NCR campus activity feed','yellow'],
 ['WORKSHOP ON ADVANCED EXCEL','School of Commerce, Finance and Accountancy','Current Delhi NCR campus activity feed','blue'],
 ['ENNOVERSE 2.0','Department of Psychology','Current Delhi NCR campus activity feed','coral'],
 ['CARNIFEST 4.0','CAPS','Current Delhi NCR campus activity feed','yellow'],
 ['THE ART & SCIENCE OF CINEMATIC LIGHTING','CDL','Current Delhi NCR campus activity feed','green'],
 ['CHANGE OF GUARD CEREMONY','NCC','Current Delhi NCR campus activity feed','coral'],
 ['THEATRE WORKSHOP','School of Psychological Sciences','Current Delhi NCR campus activity feed','blue'],
 ['STARTUP STORIES-MARKETING CLUB EVENT','School of Business and Management','Current Delhi NCR campus activity feed','green'],
 ['FINALYTICS CLUB EVENT','School of Business and Management','Current Delhi NCR campus activity feed','yellow'],
 ['PUBLIC POLICY FORMULATION WORKSHOP','School of Social Sciences','Current Delhi NCR campus activity feed','coral'],
 ['INTRODUCTORY MOOTING WORKSHOP 2026','School of Law','Current Delhi NCR campus activity feed','blue']
];
const pageNames={events:'All <em>events.</em>',today:'Today’s <em>events.</em>',week:'This <em>week.</em>',upcoming:'Upcoming <em>events.</em>',workshops:'Workshops.',hackathons:'Hackathons.',competitions:'Competitions.',lectures:'Guest <em>lectures.</em>',fests:'Cultural <em>fests.</em>',sports:'Sports.',department:'Department <em>events.</em>',club:'Club <em>events.</em>',registration:'Event <em>registration.</em>',countdown:'Event <em>countdown.</em>',calendar:'Calendar <em>view.</em>'};
const special={calendar:`<div class="student-card" style="padding:24px"><p class="eyebrow">OFFICIAL</p><h2>Academic Calendar 2026–27</h2><p class="muted">Use the university-published Delhi NCR calendar.</p><a class="action" href="academic-calendar.html">Open academic calendar →</a></div>`,countdown:`<div class="counter"><p>NEXT FEATURE</p><h2>Delhi NCR campus activity</h2><strong>LIVE</strong><p>Current activity is refreshed from the university's public campus feed.</p></div>`,registration:`<div class="student-card" style="padding:26px"><p class="eyebrow">EVENT REGISTRATION</p><h2>Register from the official event source.</h2><p class="muted">Christ Connect keeps current Delhi NCR event names visible and can link you to registration when an official registration URL is available.</p><a class="action" href="https://ncr.christuniversity.in/" target="_blank" rel="noreferrer">Open official campus site ↗</a></div>`};
const html=`<header><a class="brand" href="index.html"><span class="brand-mark">C</span> CHRIST CONNECT</a><a href="index.html">← Home</a></header><main class="wrap"><div class="head"><p class="eyebrow">DELHI NCR · CURRENT CAMPUS ACTIVITY</p><h1>${pageNames[key]||pageNames.events}</h1></div>${special[key]||`<div class="grid">${items.map(x=>`<article class="event tilt reveal"><div class="art ${x[3]}">${x[0].slice(0,1)}</div><div class="info"><small>${x[1]}</small><h3>${x[0]}</h3><p class="muted">${x[2]}. Dates, times and registration actions stay with the official source rather than invented in this app.</p><a class="action" href="https://ncr.christuniversity.in/" target="_blank" rel="noreferrer">Verify / explore ↗</a></div></article>`).join('')}</div>`}</main>`;document.body.innerHTML=html;document.body.insertAdjacentHTML('beforeend','<div class="toast" id="toast"></div>');
const toast=document.querySelector('#toast');document.querySelectorAll('.action').forEach(b=>b.addEventListener('click',()=>{toast.textContent='Opening Delhi NCR source';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1200)}));document.querySelectorAll('.tilt').forEach(el=>el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;el.style.transform=`perspective(900px) rotateX(${-y*4}deg) rotateY(${x*6}deg) translateY(-3px)`}));
