const modules={
  skill:{title:'Skill <em>Exchange.</em>',intro:'Trade knowledge, build peer connections and turn campus talent into a living network.',items:['Learn Something','Teach Something','Search Skills','Programming','Designing','Video Editing','Music','Languages','Photography','AI','Public Speaking','Others','Student Profile','Rating','Skills','Availability','Contact']},
  market:{title:'Campus <em>Marketplace.</em>',intro:'A student-to-student space for practical campus goods, pre-orders and everyday essentials.',items:['Food Pre-orders','Cafeteria','Bakery','Juice','Snacks','Meals','Coffee','Student Marketplace','Books','Calculators','Lab Coats','Electronics','Stationery','Others','Place Order','Online Payment','Cash on Pickup','Order History','Track Orders']},
  lost:{title:'Lost & <em>Found.</em>',intro:'Report, discover and reconnect with the things that move around campus.',items:['Lost Items','Found Items','Report Lost','Report Found','Search','Wallet','ID Card','Charger','Earbuds','Laptop','Watch','Bottle','Others']},
  community:{title:'Campus <em>Community.</em>',intro:'Project showcases, startup ideas, discussion spaces and stories from the student body.',items:['Student Projects','Startup Ideas','Find Team','Project Showcase','Discussion','Polls','Campus Stories','Achievements']},
  guide:{title:'Campus <em>Guide.</em>',intro:'Navigate Delhi NCR with buildings, departments, support points and practical travel context.',items:['Buildings','Departments','Auditorium','Library','Cafeteria','Labs','Sports Complex','Parking','Emergency Contacts','Interactive Map']},
  rewards:{title:'Campus <em>Rewards.</em>',intro:'Celebrate useful contributions with points, badges and community recognition.',items:['Campus Points','Badges','Leaderboard','Community Contributions','Top Mentors','Top Volunteers','Achievements']},
  notifications:{title:'Your <em>Notifications.</em>',intro:'Keep campus changes, event reminders and account activity in one quiet inbox.',items:['Event Reminder','Club Recruitment','Marketplace Updates','Lost Item Match','Skill Requests','Order Status','Campus News']},
  admin:{title:'Admin <em>Dashboard.</em>',intro:'A concept control surface for the future campus operations team.',items:['Students','Clubs','Departments','Events','Marketplace','Food Vendors','Orders','Lost & Found','Skill Exchange','Reports','Announcements','Analytics']}
};
const mod=modules[document.body.dataset.module]||modules.community;
const q=new URLSearchParams(location.search).get('section')||mod.items[0];
const campusNote=q==='Interactive Map'||document.body.dataset.module==='guide' ? '<div class="campus-note"><b>Delhi NCR campus travel</b><br><span>Nearest metro station: Shaheed Sthal NBA Metro Station · Mariam Nagar, Ghaziabad</span></div>' : '';
document.body.innerHTML=`<header><a class="brand" href="index.html"><span>C</span>CHRIST CONNECT</a><a href="index.html">← Home</a></header><main class="shell"><div class="head reveal"><div><p class="eyebrow">STUDENT PLATFORM</p><h1>${mod.title}</h1><p class="campus-note">${mod.intro}</p></div></div>${campusNote}<div class="layout"><nav class="nav">${mod.items.map(x=>`<a class="${x===q?'active':''}" href="?section=${encodeURIComponent(x)}">${x}</a>`).join('')}</nav><section class="content reveal"><p class="eyebrow">${q.toUpperCase()}</p><h2>${q}</h2><div class="cards"><div class="card"><span>✦</span><b>Explore ${q}</b><small>Campus updates and useful actions curated for the student experience.</small></div><div class="card"><span>◌</span><b>Student activity</b><small>Connect with people, opportunities and the wider campus network.</small></div><div class="card"><span>⌘</span><b>Quick action</b><small>Save this space to your account when the connected backend feature is enabled.</small></div></div><button class="action" id="action">Save to my space</button></section></div></main><div class="toast" id="toast"></div>`;
const toast=document.querySelector('#toast');document.querySelector('#action').onclick=()=>{toast.textContent=`${q} saved to your space`;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1800)};
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
